function [param] = birghtnessContrastUI()
param = [0, 0];
    d = dialog('Position',[300 300 300 180],'Name','Brightness/Contrast');
    txtBright = uicontrol('Parent', d,'Style','text',...
        'Position',[90 125 120 20],...
        'String','Brightness');
    
    sldBright = uicontrol('Parent', d,'Style', 'slider',...
        'Min',-1,'Max',1,'Value',0,...
        'Position', [60 100 180 20],...
        'Callback', @bright_callback); 
    txtContrast = uicontrol('Parent', d,'Style','text',...
        'Position',[90 70 120 20],...
        'String','Contrast');
    
    sldContrast = uicontrol('Parent', d,'Style', 'slider',...
        'Min',-1,'Max',1,'Value',0,...
        'Position', [60 45 180 20],...
        'Callback', @contrast_callback); 
     btn = uicontrol('Parent',d,...
           'Position',[60 20 70 25],...
           'String','Close',...
           'Callback','delete(gcf)');
 
   
uiwait(d);
function [] = bright_callback(source,callbackdata)
    param(1) = get(source, 'Value')
    
end

function [] = contrast_callback(source,callbackdata)
    param(2) = get(source, 'Value')
    
end
end

