function param = cannyParam()

    d = dialog('Position',[300 300 250 220],'Name','Gaussian Filter parameters');
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 150 210 40],...
           'String','Kernel Size');
    KSize =  uicontrol('Parent', d, 'Style','edit',...
             'Position', [75 140 100 25],'String','3', 'Callback', @meanValue)

    txt2 = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[25 120 210 20],...
            'String','Variance');
        
    var =  uicontrol('Parent', d, 'Style','edit',...
             'Position', [75 100 100 25],'String','0.6', 'Callback', @varValue)

   txt3 = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[25 70 210 20],...
            'String','Threshold');
        
    thresh = uicontrol('Parent', d,'Style', 'slider',...
        'Min',0,'Max',1.0,'Value',0.7,...
        'Position', [40 50 180 20],...
        'Callback', @thresh_callback); 

          
    btn = uicontrol('Parent',d,...
           'Position',[89 10 70 25],...
           'String','Apply',...
           'Callback','delete(gcf)');
   param = [3 0.6 0.7];
   
    % Wait for d to close before running to completion
    uiwait(d);
    
    function [] = meanValue(kSize, callbackdata)
      param(1) = str2num(get(kSize, 'string'));
    end

    function [] = varValue(kSize, callbackdata)
      param(2) = str2num(get(kSize, 'string'));
    end


function [] = thresh_callback(source,callbackdata)
    param(3) = get(source, 'Value')
    
end
end