function [outkSize outpad] = chooseMedian()

    d = dialog('Position',[300 300 250 180],'Name','Median parameters');
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 100 210 40],...
           'String','Pad style');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 95 100 25],...
           'String',{'indexed';'zeros';'symmetric'},...
           'Callback',@popup_callback);
    txt2 = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[25 70 210 20],...
            'String','KernelSize');
        
    kSize =  uicontrol('Parent', d, 'Style','edit',...
             'Position', [75 50 100 25],'String','5', 'Callback', @setValue)

          
    btn = uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','Apply',...
           'Callback','delete(gcf)');
    outpad = 'zeros';
    outkSize = 5;   
    % Wait for d to close before running to completion
    uiwait(d);
    
    function [] = setValue(kSize, callbackdata)
       outkSize = str2num(get(kSize, 'string'));
    end
        
   function[] = popup_callback(popup, callbackdata)
       idx = get(popup, 'Value');
       popupitem = get(popup,'String');
       outpad = popupitem(idx);
   end
end