function id = chooseFeatureMethod()

    d = dialog('Position',[300 300 250 120],'Name','Select feature type');
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 50 210 40],...
           'String','Feature type to match with');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 40 100 25],...
           'String',{'Harris';'SURF';'FAST';},...
           'Callback',@popup_callback);
          
    btn = uicontrol('Parent',d,...
           'Position',[89 10 70 25],...
           'String','Apply',...
           'Callback','delete(gcf)');
    id = 1;
   
    % Wait for d to close before running to completion
    uiwait(d);
    
        
   function[] = popup_callback(popup, callbackdata)
       idx = get(popup, 'Value');
       popupitem = get(popup,'String');
       id = idx;
   end
end