function [param1 param2 method se] = customMorph()

d = dialog('Position',[300 300 250 230],'Name','Morphing Options');

txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 180 210 40],...
    'String','Operation');

popup = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[75 170 100 25],...
    'String',{'dilate';'erode';'open'; 'close'},...
    'Callback',@popup_Methodcallback);

txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 120 210 40],...
    'String','Structuring Element');

popup = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[75 110 100 25],...
    'String',{'disk';'square';'line'; 'ball'},...
    'Callback',@popup_callback);

txt2 = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[25 85 210 20],...
    'String','Width');

width =  uicontrol('Parent', d, 'Style','edit',...
    'Position', [75 65 100 25],'String','11', 'Callback', @setWValue)

txt3 = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[25 50 210 20],...
    'String','Height');

height =  uicontrol('Parent', d, 'Style','edit',...
    'Position', [75 30 100 25],'String','-1', 'Callback', @setHValue)


btn = uicontrol('Parent',d,...
    'Position',[89 5 70 25],...
    'String','Apply',...
    'Callback','delete(gcf)');
method = 'dilate';
param1 = 11;
param2 = -1;
se = 'disk'
% Wait for d to close before running to completion
uiwait(d);

    function [] = setWValue(widthP, callbackdata)
        param1 = str2num(get(widthP, 'string'));
    end

    function [] = setHValue(htP, callbackdata)
        param2 = str2num(get(htP, 'string'));
    end

    function[] = popup_callback(popup, callbackdata)
        idx = get(popup, 'Value');
        popupitem = get(popup,'String');
        se = popupitem(idx);
    end

function[] = popup_Methodcallback(popup, callbackdata)
        idx = get(popup, 'Value');
        popupitem = get(popup,'String');
        method = popupitem(idx);
    end
end