function [param] = sharpenParams()
param = [0, 0];
    d = dialog('Position',[300 300 300 200],'Name','Sharpen');
    txtBright = uicontrol('Parent', d,'Style','text',...
        'Position',[90 160 120 20],...
        'String','Radius');
    
    sldBright = uicontrol('Parent', d,'Style', 'slider',...
        'Min',0,'Max',1,'Value',0.5,...
        'Position', [60 145 180 20],...
        'Callback', @Rad_callback); 
    txtContrast = uicontrol('Parent', d,'Style','text',...
        'Position',[90 115 120 20],...
        'String','Amount');
    
    sldContrast = uicontrol('Parent', d,'Style', 'slider',...
        'Min',0,'Max',1.0,'Value',0.5,...
        'Position', [60 95 180 20],...
        'Callback', @Amt_callback); 
    
    txtContrast = uicontrol('Parent', d,'Style','text',...
        'Position',[90 65 120 20],...
        'String','Threshold');
    
    sldContrast = uicontrol('Parent', d,'Style', 'slider',...
        'Min',0,'Max',1.0,'Value',0.5,...
        'Position', [60 45 180 20],...
        'Callback', @thresh_callback); 
     btn = uicontrol('Parent',d,...
           'Position',[60 20 70 25],...
           'String','Apply',...
           'Callback','delete(gcf)');
 
   param = [0.5 0.5 0.5];
uiwait(d);
function [] = Rad_callback(source,callbackdata)
    param(1) = get(source, 'Value')
    
end

function [] = Amt_callback(source,callbackdata)
    param(2) = get(source, 'Value')
end 
    function [] = thresh_callback(source,callbackdata)
    param(3) = get(source, 'Value')
end
end

